//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyLabsApp.RegexCheckerReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegexCheckerReference.RegexChecker1Soap")]
    public interface RegexChecker1Soap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNickname", ReplyAction="*")]
        StudyLabsApp.RegexCheckerReference.CheckNicknameResponse CheckNickname(StudyLabsApp.RegexCheckerReference.CheckNicknameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNickname", ReplyAction="*")]
        System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckNicknameResponse> CheckNicknameAsync(StudyLabsApp.RegexCheckerReference.CheckNicknameRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLink", ReplyAction="*")]
        StudyLabsApp.RegexCheckerReference.CheckLinkResponse CheckLink(StudyLabsApp.RegexCheckerReference.CheckLinkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckLink", ReplyAction="*")]
        System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckLinkResponse> CheckLinkAsync(StudyLabsApp.RegexCheckerReference.CheckLinkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckNicknameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckNickname", Namespace="http://tempuri.org/", Order=0)]
        public StudyLabsApp.RegexCheckerReference.CheckNicknameRequestBody Body;
        
        public CheckNicknameRequest() {
        }
        
        public CheckNicknameRequest(StudyLabsApp.RegexCheckerReference.CheckNicknameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckNicknameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public CheckNicknameRequestBody() {
        }
        
        public CheckNicknameRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckNicknameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckNicknameResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudyLabsApp.RegexCheckerReference.CheckNicknameResponseBody Body;
        
        public CheckNicknameResponse() {
        }
        
        public CheckNicknameResponse(StudyLabsApp.RegexCheckerReference.CheckNicknameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckNicknameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckNicknameResult;
        
        public CheckNicknameResponseBody() {
        }
        
        public CheckNicknameResponseBody(bool CheckNicknameResult) {
            this.CheckNicknameResult = CheckNicknameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLink", Namespace="http://tempuri.org/", Order=0)]
        public StudyLabsApp.RegexCheckerReference.CheckLinkRequestBody Body;
        
        public CheckLinkRequest() {
        }
        
        public CheckLinkRequest(StudyLabsApp.RegexCheckerReference.CheckLinkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLinkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public CheckLinkRequestBody() {
        }
        
        public CheckLinkRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckLinkResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudyLabsApp.RegexCheckerReference.CheckLinkResponseBody Body;
        
        public CheckLinkResponse() {
        }
        
        public CheckLinkResponse(StudyLabsApp.RegexCheckerReference.CheckLinkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckLinkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckLinkResult;
        
        public CheckLinkResponseBody() {
        }
        
        public CheckLinkResponseBody(bool CheckLinkResult) {
            this.CheckLinkResult = CheckLinkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegexChecker1SoapChannel : StudyLabsApp.RegexCheckerReference.RegexChecker1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegexChecker1SoapClient : System.ServiceModel.ClientBase<StudyLabsApp.RegexCheckerReference.RegexChecker1Soap>, StudyLabsApp.RegexCheckerReference.RegexChecker1Soap {
        
        public RegexChecker1SoapClient() {
        }
        
        public RegexChecker1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegexChecker1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegexChecker1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegexChecker1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudyLabsApp.RegexCheckerReference.CheckNicknameResponse StudyLabsApp.RegexCheckerReference.RegexChecker1Soap.CheckNickname(StudyLabsApp.RegexCheckerReference.CheckNicknameRequest request) {
            return base.Channel.CheckNickname(request);
        }
        
        public bool CheckNickname(string input) {
            StudyLabsApp.RegexCheckerReference.CheckNicknameRequest inValue = new StudyLabsApp.RegexCheckerReference.CheckNicknameRequest();
            inValue.Body = new StudyLabsApp.RegexCheckerReference.CheckNicknameRequestBody();
            inValue.Body.input = input;
            StudyLabsApp.RegexCheckerReference.CheckNicknameResponse retVal = ((StudyLabsApp.RegexCheckerReference.RegexChecker1Soap)(this)).CheckNickname(inValue);
            return retVal.Body.CheckNicknameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckNicknameResponse> StudyLabsApp.RegexCheckerReference.RegexChecker1Soap.CheckNicknameAsync(StudyLabsApp.RegexCheckerReference.CheckNicknameRequest request) {
            return base.Channel.CheckNicknameAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckNicknameResponse> CheckNicknameAsync(string input) {
            StudyLabsApp.RegexCheckerReference.CheckNicknameRequest inValue = new StudyLabsApp.RegexCheckerReference.CheckNicknameRequest();
            inValue.Body = new StudyLabsApp.RegexCheckerReference.CheckNicknameRequestBody();
            inValue.Body.input = input;
            return ((StudyLabsApp.RegexCheckerReference.RegexChecker1Soap)(this)).CheckNicknameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudyLabsApp.RegexCheckerReference.CheckLinkResponse StudyLabsApp.RegexCheckerReference.RegexChecker1Soap.CheckLink(StudyLabsApp.RegexCheckerReference.CheckLinkRequest request) {
            return base.Channel.CheckLink(request);
        }
        
        public bool CheckLink(string input) {
            StudyLabsApp.RegexCheckerReference.CheckLinkRequest inValue = new StudyLabsApp.RegexCheckerReference.CheckLinkRequest();
            inValue.Body = new StudyLabsApp.RegexCheckerReference.CheckLinkRequestBody();
            inValue.Body.input = input;
            StudyLabsApp.RegexCheckerReference.CheckLinkResponse retVal = ((StudyLabsApp.RegexCheckerReference.RegexChecker1Soap)(this)).CheckLink(inValue);
            return retVal.Body.CheckLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckLinkResponse> StudyLabsApp.RegexCheckerReference.RegexChecker1Soap.CheckLinkAsync(StudyLabsApp.RegexCheckerReference.CheckLinkRequest request) {
            return base.Channel.CheckLinkAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudyLabsApp.RegexCheckerReference.CheckLinkResponse> CheckLinkAsync(string input) {
            StudyLabsApp.RegexCheckerReference.CheckLinkRequest inValue = new StudyLabsApp.RegexCheckerReference.CheckLinkRequest();
            inValue.Body = new StudyLabsApp.RegexCheckerReference.CheckLinkRequestBody();
            inValue.Body.input = input;
            return ((StudyLabsApp.RegexCheckerReference.RegexChecker1Soap)(this)).CheckLinkAsync(inValue);
        }
    }
}
