//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyLabsApp.ServiceReferenceDB {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDB.WebService2Soap")]
    public interface WebService2Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindExistingPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FindExistingPerson(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindExistingPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> FindExistingPersonAsync(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LoadData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> LoadDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEntryToDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddEntryToDatabase(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEntryToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task AddEntryToDatabaseAsync(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy entry);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AStuddyBuddy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nicknameField;
        
        private string linkField;
        
        private string facultyField;
        
        private string studiesField;
        
        private int statusField;
        
        private int pointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("Nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("Link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Faculty {
            get {
                return this.facultyField;
            }
            set {
                this.facultyField = value;
                this.RaisePropertyChanged("Faculty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Studies {
            get {
                return this.studiesField;
            }
            set {
                this.studiesField = value;
                this.RaisePropertyChanged("Studies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Points {
            get {
                return this.pointsField;
            }
            set {
                this.pointsField = value;
                this.RaisePropertyChanged("Points");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService2SoapChannel : StudyLabsApp.ServiceReferenceDB.WebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService2SoapClient : System.ServiceModel.ClientBase<StudyLabsApp.ServiceReferenceDB.WebService2Soap>, StudyLabsApp.ServiceReferenceDB.WebService2Soap {
        
        public WebService2SoapClient() {
        }
        
        public WebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool FindExistingPerson(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy person) {
            return base.Channel.FindExistingPerson(person);
        }
        
        public System.Threading.Tasks.Task<bool> FindExistingPersonAsync(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy person) {
            return base.Channel.FindExistingPersonAsync(person);
        }
        
        public System.Data.DataTable LoadData() {
            return base.Channel.LoadData();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> LoadDataAsync() {
            return base.Channel.LoadDataAsync();
        }
        
        public void AddEntryToDatabase(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy entry) {
            base.Channel.AddEntryToDatabase(entry);
        }
        
        public System.Threading.Tasks.Task AddEntryToDatabaseAsync(StudyLabsApp.ServiceReferenceDB.AStuddyBuddy entry) {
            return base.Channel.AddEntryToDatabaseAsync(entry);
        }
    }
}
