//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyLabsApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Faculties_and_studies {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Faculties_and_studies() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyLabsApp.Resources.Faculties_and_studies", typeof(Faculties_and_studies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Accounting_and_Auditing {
            get {
                return ResourceManager.GetString("Accounting and Auditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Advanced_Technology_Physics_and_Management {
            get {
                return ResourceManager.GetString("Advanced Technology Physics and Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Applied_Physics {
            get {
                return ResourceManager.GetString("Applied Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Archeology {
            get {
                return ResourceManager.GetString("Archeology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Asian_Studies__Japan_ {
            get {
                return ResourceManager.GetString("Asian Studies (Japan)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Asian_studies__Middle_Eastern_Studies_ {
            get {
                return ResourceManager.GetString("Asian studies (Middle Eastern Studies)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Asian_Studies__Sinology_ {
            get {
                return ResourceManager.GetString("Asian Studies (Sinology)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Asian_Studies__South_Asian_Studies_ {
            get {
                return ResourceManager.GetString("Asian Studies (South Asian Studies)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Audiovisual_Translation {
            get {
                return ResourceManager.GetString("Audiovisual Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Biochemistry {
            get {
                return ResourceManager.GetString("Biochemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Bioinformatics {
            get {
                return ResourceManager.GetString("Bioinformatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Biology {
            get {
                return ResourceManager.GetString("Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Business_and_law {
            get {
                return ResourceManager.GetString("Business and law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Business_Finance {
            get {
                return ResourceManager.GetString("Business Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Business_Information_Management {
            get {
                return ResourceManager.GetString("Business Information Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Business_Information_Systems {
            get {
                return ResourceManager.GetString("Business Information Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Chemistry {
            get {
                return ResourceManager.GetString("Chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Childhood_Pedagogy_Motivation_Assessment__Pre_school_Pedagogy__Session_Arrangement_ {
            get {
                return ResourceManager.GetString("Childhood Pedagogy Motivation Assessment (Pre-school Pedagogy, Session Arrangemen" +
                        "t)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Childhood_Pedagogy_Motivation_Assessment__Primary_Education_Pedagogy__Session_Arrangement_ {
            get {
                return ResourceManager.GetString("Childhood Pedagogy Motivation Assessment (Primary Education Pedagogy, Session Arr" +
                        "angement)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Childhood_Pedagogy_Motivation_Assessment__specializations__Primary_Education_or_Pre_primary_Education_ {
            get {
                return ResourceManager.GetString("Childhood Pedagogy Motivation Assessment (specializations: Primary Education or P" +
                        "re-primary Education)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Classical__Latin_and_Ancient_Greek__Philology {
            get {
                return ResourceManager.GetString("Classical (Latin and Ancient Greek) Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Computer_Physics_and_Modeling {
            get {
                return ResourceManager.GetString("Computer Physics and Modeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Creative_Communication {
            get {
                return ResourceManager.GetString("Creative Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Criminology {
            get {
                return ResourceManager.GetString("Criminology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Cultural_History_and_Anthropology {
            get {
                return ResourceManager.GetString("Cultural History and Anthropology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Data_science {
            get {
                return ResourceManager.GetString("Data science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Dentistry {
            get {
                return ResourceManager.GetString("Dentistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Econometrics {
            get {
                return ResourceManager.GetString("Econometrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Economics {
            get {
                return ResourceManager.GetString("Economics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Economics_and_Management {
            get {
                return ResourceManager.GetString("Economics and Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Electronics_and_Telecommunication_Technologies {
            get {
                return ResourceManager.GetString("Electronics and Telecommunication Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_and_other_foreign__French__language {
            get {
                return ResourceManager.GetString("English and other foreign (French) language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_and_other_foreign__Norwegian__language {
            get {
                return ResourceManager.GetString("English and other foreign (Norwegian) language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_and_other_foreign__Russian__language {
            get {
                return ResourceManager.GetString("English and other foreign (Russian) language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_and_other_foreign__Russian__language__In_English_and_Russian_ {
            get {
                return ResourceManager.GetString("English and other foreign (Russian) language (In English and Russian)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_and_other_foreign__Spanish__language {
            get {
                return ResourceManager.GetString("English and other foreign (Spanish) language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string English_and_other_foreign__Swedish__language {
            get {
                return ResourceManager.GetString("English and other foreign (Swedish) language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string English_philology {
            get {
                return ResourceManager.GetString("English philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Environmental_Science_and_Environment {
            get {
                return ResourceManager.GetString("Environmental Science and Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Ergotherapy {
            get {
                return ResourceManager.GetString("Ergotherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Finance_and_Accounting_Applications {
            get {
                return ResourceManager.GetString("Finance and Accounting Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Financial_and_Actuarial_Mathematics {
            get {
                return ResourceManager.GetString("Financial and Actuarial Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string French_Philology {
            get {
                return ResourceManager.GetString("French Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Genetics {
            get {
                return ResourceManager.GetString("Genetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Geography {
            get {
                return ResourceManager.GetString("Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Geology {
            get {
                return ResourceManager.GetString("Geology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string German_Philology {
            get {
                return ResourceManager.GetString("German Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Informatics {
            get {
                return ResourceManager.GetString("Informatics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Information_Systems_and_Cybersecurity {
            get {
                return ResourceManager.GetString("Information Systems and Cybersecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Information_Systems_and_Cybersecurity__in_English_ {
            get {
                return ResourceManager.GetString("Information Systems and Cybersecurity (in English)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Information_Technologies {
            get {
                return ResourceManager.GetString("Information Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Information_Technology_Engineering {
            get {
                return ResourceManager.GetString("Information Technology Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string International_Business {
            get {
                return ResourceManager.GetString("International Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string International_Business__in_English_ {
            get {
                return ResourceManager.GetString("International Business (in English)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Italian_Philology {
            get {
                return ResourceManager.GetString("Italian Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Journalism {
            get {
                return ResourceManager.GetString("Journalism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Kartography_and_geographical_information_systems {
            get {
                return ResourceManager.GetString("Kartography and geographical information systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Law {
            get {
                return ResourceManager.GetString("Law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Light_technologies {
            get {
                return ResourceManager.GetString("Light technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Lithuanian_Philology {
            get {
                return ResourceManager.GetString("Lithuanian Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Lithuanian_Philology_and_Advertising {
            get {
                return ResourceManager.GetString("Lithuanian Philology and Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Lithuanian_Philology_and_Estonian_language {
            get {
                return ResourceManager.GetString("Lithuanian Philology and Estonian language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Lithuanian_Philology_and_Latvian_language {
            get {
                return ResourceManager.GetString("Lithuanian Philology and Latvian language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Lithuanian_Philology_and_New_Greek_language {
            get {
                return ResourceManager.GetString("Lithuanian Philology and New Greek language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Lithuanian_Philology_ir_Turkish_language {
            get {
                return ResourceManager.GetString("Lithuanian Philology ir Turkish language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Management_of_Cultural_and_Creative_Industries {
            get {
                return ResourceManager.GetString("Management of Cultural and Creative Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Marketing_and_Global_Business {
            get {
                return ResourceManager.GetString("Marketing and Global Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Mathematics_and_Applications_of_Mathematics {
            get {
                return ResourceManager.GetString("Mathematics and Applications of Mathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Meteorology_and_hydrology {
            get {
                return ResourceManager.GetString("Meteorology and hydrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Microbiology {
            get {
                return ResourceManager.GetString("Microbiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Molecular_Biology {
            get {
                return ResourceManager.GetString("Molecular Biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Nanomaterials_chemistry {
            get {
                return ResourceManager.GetString("Nanomaterials chemistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string Neurobiophysics {
            get {
                return ResourceManager.GetString("Neurobiophysics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Nursing {
            get {
                return ResourceManager.GetString("Nursing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Philosophy {
            get {
                return ResourceManager.GetString("Philosophy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Physics {
            get {
                return ResourceManager.GetString("Physics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Physiotherapy {
            get {
                return ResourceManager.GetString("Physiotherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Polish_Philology {
            get {
                return ResourceManager.GetString("Polish Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string Politics_Studies {
            get {
                return ResourceManager.GetString("Politics Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Psychology {
            get {
                return ResourceManager.GetString("Psychology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Psychology__with_higher_education_ {
            get {
                return ResourceManager.GetString("Psychology (with higher education)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Public_Health {
            get {
                return ResourceManager.GetString("Public Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Publishing_and_Advertising {
            get {
                return ResourceManager.GetString("Publishing and Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Quantitative_Economics {
            get {
                return ResourceManager.GetString("Quantitative Economics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Russian_Philology {
            get {
                return ResourceManager.GetString("Russian Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Scandinavian_Studies__Danish___Norwegian___Swedish_ {
            get {
                return ResourceManager.GetString("Scandinavian Studies (Danish / Norwegian / Swedish)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Scandinavian_Studies__Finnish_and_Swedish_ {
            get {
                return ResourceManager.GetString("Scandinavian Studies (Finnish and Swedish)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Science_Education__Biology_ {
            get {
                return ResourceManager.GetString("Science Education (Biology)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Science_Education__Chemistry_ {
            get {
                return ResourceManager.GetString("Science Education (Chemistry)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Science_Education__Physics_ {
            get {
                return ResourceManager.GetString("Science Education (Physics)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Social_politics {
            get {
                return ResourceManager.GetString("Social politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Social_work {
            get {
                return ResourceManager.GetString("Social work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Sociology {
            get {
                return ResourceManager.GetString("Sociology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Software_Engineering {
            get {
                return ResourceManager.GetString("Software Engineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Spanish_Philology {
            get {
                return ResourceManager.GetString("Spanish Philology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Translation__English_to_Lithuanian_to_English_and_Latvian_to_Lithuanian_ {
            get {
                return ResourceManager.GetString("Translation (English to Lithuanian to English and Latvian to Lithuanian)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Translation__English_to_Lithuanian_to_English_and_Spanish_to_Lithuanian_ {
            get {
                return ResourceManager.GetString("Translation (English to Lithuanian to English and Spanish to Lithuanian)", resourceCulture);
            }
        }
    }
}
